export const dataBanner = JSON.parse(`{
    "page": 1,
    "results": [
        {
            "backdrop_path": "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
            "first_air_date": "2023-01-15",
            "genre_ids": [18],
            "id": 100088,
            "name": "The Last of Us",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "The Last of Us",
            "overview": "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
            "popularity": 2372.319,
            "poster_path": "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
            "vote_average": 8.8,
            "vote_count": 2899
        },
        {
            "backdrop_path": "/xgZ9AhvXqi9aSDWzCpoC9JAkLPY.jpg",
            "first_air_date": "2019-01-01",
            "genre_ids": [35],
            "id": 85425,
            "name": "Dear Heirs",
            "origin_country": ["HU"],
            "original_language": "hu",
            "original_name": "Drága örökösök",
            "overview": "Hungarian remake of the Bulgarian series about a disconnect family living together in order to get an inheritance.",
            "popularity": 1179.155,
            "poster_path": "/xDOUahrwEsgDlejXjZLc9lOljSx.jpg",
            "vote_average": 5.3,
            "vote_count": 7
        },
        {
            "backdrop_path": "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
            "first_air_date": "2019-11-12",
            "genre_ids": [10765, 10759, 18],
            "id": 82856,
            "name": "The Mandalorian",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "The Mandalorian",
            "overview": "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
            "popularity": 1422.98,
            "poster_path": "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
            "vote_average": 8.5,
            "vote_count": 8635
        },
        {
            "backdrop_path": null,
            "first_air_date": "2015-03-25",
            "genre_ids": [10764],
            "id": 136598,
            "name": "First Dates NL",
            "origin_country": ["NL"],
            "original_language": "nl",
            "original_name": "First Dates NL",
            "overview": "",
            "popularity": 964.371,
            "poster_path": "/48CLPsZ1HRFFSGfZx2SY7FHihyC.jpg",
            "vote_average": 5,
            "vote_count": 1
        },
        {
            "backdrop_path": "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
            "first_air_date": "2005-03-27",
            "genre_ids": [18],
            "id": 1416,
            "name": "Grey's Anatomy",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "Grey's Anatomy",
            "overview": "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
            "popularity": 1252.151,
            "poster_path": "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
            "vote_average": 8.3,
            "vote_count": 8996
        },
        {
            "backdrop_path": "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
            "first_air_date": "2021-08-03",
            "genre_ids": [10766],
            "id": 130542,
            "name": "Bhagya Lakshmi",
            "origin_country": ["IN"],
            "original_language": "hi",
            "original_name": "Bhagya Lakshmi",
            "overview": "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
            "popularity": 752.327,
            "poster_path": "/7wuKrFvbX7kAIF0ctotARsqayPo.jpg",
            "vote_average": 5,
            "vote_count": 33
        },
        {
            "backdrop_path": "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
            "first_air_date": "2023-01-23",
            "genre_ids": [9648, 18],
            "id": 202250,
            "name": "Dirty Linen",
            "origin_country": ["PH"],
            "original_language": "tl",
            "original_name": "Dirty Linen",
            "overview": "To exact vengeance, a young woman infiltrates the household of an influential family as a housemaid to expose their dirty secrets. However, love will get in the way of her revenge plot.",
            "popularity": 735.139,
            "poster_path": "/ujlkQtHAVShWyWTloGU2Vh5Jbo9.jpg",
            "vote_average": 4.9,
            "vote_count": 8
        },
        {
            "backdrop_path": "/1vgdmeW6keP47DQ1tGwfVCdUKqu.jpg",
            "first_air_date": "2020-10-12",
            "genre_ids": [35],
            "id": 111551,
            "name": "Haireta mou ton Platano",
            "origin_country": ["GR"],
            "original_language": "el",
            "original_name": "Χαιρέτα μου τον Πλάτανο",
            "overview": "The small Greek village of Platanos (Plane Tree) buries the elderly recluse Vangelas and notifies the deceased's estranged children and grandchildren about his death. Vangela's will leaves 3 million euros to his family, but requires them to move to the village and obey certain terms in order to inherit.",
            "popularity": 693.755,
            "poster_path": "/vAu6or1W4G1q7wJxQfDmATtnIg.jpg",
            "vote_average": 5.5,
            "vote_count": 8
        },
        {
            "backdrop_path": "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
            "first_air_date": "2022-11-02",
            "genre_ids": [18],
            "id": 213713,
            "name": "Faltu",
            "origin_country": ["IN"],
            "original_language": "hi",
            "original_name": "Faltu",
            "overview": "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
            "popularity": 1464.404,
            "poster_path": "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
            "vote_average": 5.3,
            "vote_count": 13
        },
        {
            "backdrop_path": "/jIV5weV19wH02rnuWyMtYI4dYC8.jpg",
            "first_air_date": "2023-02-13",
            "genre_ids": [10759, 35, 18],
            "id": 215803,
            "name": "Batang Quiapo",
            "origin_country": ["PH"],
            "original_language": "tl",
            "original_name": "Batang Quiapo",
            "overview": "A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.",
            "popularity": 606.32,
            "poster_path": "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
            "vote_average": 7.3,
            "vote_count": 4
        },
        {
            "backdrop_path": "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
            "first_air_date": "2023-01-04",
            "genre_ids": [18, 10751],
            "id": 215103,
            "name": "Teri Meri Doriyaann",
            "origin_country": ["IN"],
            "original_language": "hi",
            "original_name": "तेरी मेरी डोरियाँ",
            "overview": "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
            "popularity": 1406.867,
            "poster_path": "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
            "vote_average": 8,
            "vote_count": 2
        },
        {
            "backdrop_path": "/dLLafkr4khRj00fvQjZ46oPsY43.jpg",
            "first_air_date": "2022-11-28",
            "genre_ids": [18],
            "id": 215315,
            "name": "Rabb Se Hai Dua",
            "origin_country": ["IN"],
            "original_language": "hi",
            "original_name": "Rabb Se Hai Dua",
            "overview": "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
            "popularity": 583.413,
            "poster_path": "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
            "vote_average": 10,
            "vote_count": 1
        },
        {
            "backdrop_path": "/iN9uULLaSx7h21tcR9io2dnARjw.jpg",
            "first_air_date": "2013-04-15",
            "genre_ids": [80, 18, 10766],
            "id": 44953,
            "name": "The Lord of the Skies",
            "origin_country": ["MX"],
            "original_language": "es",
            "original_name": "El señor de los cielos",
            "overview": "Set in the 1990s, these are the life and times of Amado Carrillo Fuentes, a man who became the head of the Juárez cartel. Nicknamed “El Señor de los Cielos” (Lord of the Skies) because of the large fleet of airplanes he used to transport drugs, he was also known for washing more than $200 million through Colombia to finance his huge fleet. He is described as the most powerful drug trafficker of his time.",
            "popularity": 917.876,
            "poster_path": "/Ag7VUdnrRz5Qpq3Yn3E5OCvFnu0.jpg",
            "vote_average": 7.9,
            "vote_count": 2476
        },
        {
            "backdrop_path": "/3r6rV0tGI2BtVgqc4e65Gh4hVXO.jpg",
            "first_air_date": "2023-02-20",
            "genre_ids": [10766],
            "id": 220992,
            "name": "Impossible Love",
            "origin_country": ["MX"],
            "original_language": "es",
            "original_name": "El amor invencible",
            "overview": "After losing all her loved ones fifteen years ago and believing her babies were killed at the hands of the father of her first love, Leona Bravo (Angelique Boyer) embarks on a journey of justice against all those who hurt her. In this process, Leona discovers that her children are actually alive and is reunited with an old friend with whom she finds true love. As a result, she will be torn between her desire for justice and rebuilding her bond with her two children, as well as regaining her faith in love.",
            "popularity": 760.175,
            "poster_path": "/5ea9hJqaImtakNpeet9DI2yhy4g.jpg",
            "vote_average": 6,
            "vote_count": 2
        },
        {
            "backdrop_path": "/zJNEXWx3YyWGQioCbutFd5dcNYS.jpg",
            "first_air_date": "2022-03-21",
            "genre_ids": [10766, 10759, 10751],
            "id": 157059,
            "name": "Poliana Moça",
            "origin_country": ["BR"],
            "original_language": "pt",
            "original_name": "Poliana Moça",
            "overview": "",
            "popularity": 561.643,
            "poster_path": "/sSRFeVwpyUffmqvreVbbNILHYbY.jpg",
            "vote_average": 6.5,
            "vote_count": 22
        },
        {
            "backdrop_path": "/nTB21wfQPX1IirpGXTmxr2VsWTC.jpg",
            "first_air_date": "1955-11-26",
            "genre_ids": [],
            "id": 221053,
            "name": "Zeit im Bild",
            "origin_country": ["DE"],
            "original_language": "de",
            "original_name": "Zeit im Bild",
            "overview": "",
            "popularity": 1291.255,
            "poster_path": "/axK66NpM828m1vdBvsfYZaXadIp.jpg",
            "vote_average": 4,
            "vote_count": 4
        },
        {
            "backdrop_path": "/iQ6ANV7F7I6Lc8rTLSEwDkOO37Q.jpg",
            "first_air_date": "1988-05-02",
            "genre_ids": [],
            "id": 221056,
            "name": "Tirol Heute",
            "origin_country": ["DE"],
            "original_language": "de",
            "original_name": "Tirol Heute",
            "overview": "",
            "popularity": 1272.989,
            "poster_path": null,
            "vote_average": 5,
            "vote_count": 1
        },
        {
            "backdrop_path": null,
            "first_air_date": "2023-02-16",
            "genre_ids": [18],
            "id": 221443,
            "name": "星落凝结成糖",
            "origin_country": ["CN"],
            "original_language": "zh",
            "original_name": "星落凝结成糖",
            "overview": "",
            "popularity": 1233.023,
            "poster_path": "/gT0LvxbLSacXtLy27WmxBMwZjos.jpg",
            "vote_average": 0,
            "vote_count": 0
        },
        {
            "backdrop_path": null,
            "first_air_date": "2021-10-27",
            "genre_ids": [18],
            "id": 197109,
            "name": "Yeh Rishta Kya Kehlata Hai",
            "origin_country": ["IN"],
            "original_language": "hi",
            "original_name": "ये रिश्ता क्या कहलाता है",
            "overview": "A personal tragedy creates a rift in Abhimanyu and Akshara's marital life. Years later, when destiny offers a second chance, will the duo embrace love?",
            "popularity": 1219.716,
            "poster_path": "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
            "vote_average": 4.9,
            "vote_count": 16
        },
        {
            "backdrop_path": "/4nXqYVnUJImG0HOAQ2QIryknuMC.jpg",
            "first_air_date": "2023-03-14",
            "genre_ids": [10759, 18],
            "id": 195868,
            "name": "Gotham Knights",
            "origin_country": ["US"],
            "original_language": "en",
            "original_name": "Gotham Knights",
            "overview": "In the aftermath of Bruce Wayne's murder, his rebellious adopted son forges an unlikely alliance with the children of Batman's enemies when they are all framed for killing the Caped Crusader.",
            "popularity": 970.724,
            "poster_path": "/tbCGmkR3TRDug4weDnHEGCu3WEC.jpg",
            "vote_average": 8.3,
            "vote_count": 15
        }
    ],
    "total_pages": 7325,
    "total_results": 146491
}`)
